spring:
  mail:
    host: smtp.qq.com
    username: 2832009432@qq.com
    password: kqxforibwvxdddgg
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          prot: 465    #465 587
        starttls:
          enable: true
          required: true
        ssl:
          enable: true
    default-encoding: UTF-8