#logging:
#  pattern:
##    ????????????
#    console: "%yellow(%d{yyyy-MM-dd}) %clr([%thread]){blue} %clr(%-5level){magenta} %logger - %msg%n"
#    file: "%yellow(%d{yyyy-MM-dd}) %clr([%thread]){blue} %clr(%-5level){magenta} %logger - %msg%n"
spring:
  profiles:
    active: prod