file:
  upload-path: C:\Users\HP\Desktop\upload\

spring:
  web:
    resources:
    static-locations: classpath:/static/,file:$(web.upload-path)
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760

minio:
  endPoint: http://43.137.12.232:9000
  accessKey: admin
  secretKey: 12345678
